apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: rag-system
spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: mher/flower:2.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5555
          env:
            - name: CELERY_BROKER_URL
              value: "redis://redis-service:6379/1"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-service:6379/1"